remote_theme: bchilton9/chilsoft-theme
plugins:
  - jekyll-remote-theme
# github repo theme above. Not required for the theme park switcher
#
# one line controls every app:
current_theme: overseerr
# Available Theme.park Themes:
# - aquamarine
# - dark
# - dracula
# - hotline
# - hotpink
# - maroon
# - nord
# - organizr
# - overseerr
# - plex
# - space-gray